CREATE TABLE [Majors](
	[MajorID] INT PRIMARY KEY NOT NULL,
	[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE [Students](
	[StudentID] INT PRIMARY KEY NOT NULL,
	[StudentNumber] VARCHAR(30) NOT NULL,
	[StudentName] VARCHAR(30) NOT NULL,
	[MajorID] INT FOREIGN KEY REFERENCES [Majors]([MajorID]) NOT NULL
)

CREATE TABLE [Subjects](
	[SubjectID] INT PRIMARY KEY NOT NULL,
	[SubjectName] VARCHAR(30) NOT NULL
)

CREATE TABLE [Agenda](
	[StudentID] INT FOREIGN KEY REFERENCES [Students]([StudentID]) NOT NULL,
	[SubjectID] INT FOREIGN KEY REFERENCES [Subjects]([SubjectID]) NOT NULL,
	PRIMARY KEY([StudentID], [SubjectID])
)

CREATE TABLE [Payments](
	[PaymentID] INT PRIMARY KEY NOT NULL,
	[PaymentDate] DATE NOT NULL,
	[PaymentAmount] DECIMAL(9, 2) NOT NULL,
	[StudentID] INT FOREIGN KEY REFERENCES [Students]([StudentID]) NOT NULL
)